upstream rails_app {
  server app:3000;
}

server {
  listen 80;
  server_name rails.localhost;

  root /rails/public;

  location / {
    proxy_pass http://rails_app;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location ~ /\. {
    deny all;
  }

    error_log /var/log/nginx/api_error.log;
    access_log /var/log/nginx/api_access.log main;
}
