# This is the configuration file for the database connections in a Rails application.
# It uses environment variables to dynamically set the database connection parameters
# for different environments (development, test, production).

default: &default
  # The database adapter to be used (e.g., postgresql, mysql, sqlite3).
  adapter:  postgresql
  encoding: unicode
  host:     database
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  database: <%= ENV.fetch("DB_DATABASE") %>
  port:     <%= ENV.fetch("DB_PORT") %>
  pool:     5
  timeout:  5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default